= Columnar SDK Release Notes
:description: Release notes, brief installation instructions, and download archive for the Capella Columnar Python Client.
:navtitle: Release Notes
:page-toclevels: 2
:page-aliases: sdk-release-notes.adoc

// tag::all[]
[abstract]
{description}

Version {sdk_dot_minor} of the Java columnar SDK implements the {sdk_api} xref:compatibility.adoc#api-version[SDK API].
See the xref:compatibility.html#couchbase-feature-availability-matrix[compatibility pages] for more information on feature compatibility with different versions of Capella columnar.


== Installation

See the xref:project-docs:sdk-full-installation.adoc[Full Installation] guide for details.

// tag::all[]


[#latest-release]
== Python Columnar SDK 1.0 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.


=== Version 1.0.1 (10 October 2025)

Version 1.0.1 is the next patch release of the first generation Couchbase Columnar Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase-columnar==1.0.1
----

*API Docs:* https://docs.couchbase.com/sdk-api/columnar-python-client-1.0.1/

==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCO-42[PYCO-42]:
Added support for Python 3.13.

* https://jira.issues.couchbase.com/browse/PYCO-86[PYCO-86]:
Updated SDK to more recent {cpp} core.

* https://jira.issues.couchbase.com/browse/PYCO-88[PYCO-88]:
Stopped publishing wheel for EOL Python 3.8.

* https://jira.issues.couchbase.com/browse/PYCO-90[PYCO-90]:
Improved `ColumnarError` `__repr__()`.

==== Fixes

* https://jira.issues.couchbase.com/browse/PYCO-44[PYCO-44],
* https://jira.issues.couchbase.com/browse/PYCO-84[PYCO-84]:
Fixed dispatch timer to cancel after request has been successfully sent to server.

* https://jira.issues.couchbase.com/browse/PYCO-83[PYCO-83],
* https://jira.issues.couchbase.com/browse/PYCO-85[PYCO-85]:
Fixed potential crash during scaling scenarios.

* https://jira.issues.couchbase.com/browse/PYCO-89[PYCO-89]:
The internal `QueryOperationCanceledError` is no longer raised. Instead, `ColumnarError` is raised.


=== Version 1.0.0 (11 October 2024)

This is the first General Availability (GA) release of the new Couchbase Columnar Python SDK.
It supports executing queries against Capella Columnar clusters, with additional features planned for future releases.

https://docs.couchbase.com/sdk-api/columnar-python-client-1.0.0/[API Reference]
// end::all[]
