= Columnar SDK Release Notes
:description: Release notes, brief installation instructions, and download archive for the Capella Columnar Java Client.
:navtitle: Release Notes
:page-toclevels: 2
:page-aliases: sdk-release-notes.adoc

// tag::all[]
[abstract]
{description}

Version {sdk_dot_minor} of the Java columnar SDK implements the {sdk_api} xref:compatibility.adoc#api-version[SDK API].
See the xref:compatibility.html#couchbase-feature-availability-matrix[compatibility pages] for more information on feature compatibility with different versions of Capella columnar.


== Installation

See the xref:project-docs:sdk-full-installation.adoc[Full Installation] guide for details.

// tag::all[]


[#latest-release]
== Java Columnar SDK 1.0 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.


=== Version 1.0.0 (ZZZ October 2024)

First GA release of the Java columnar SDK.

TODO - correct api ref??

https://docs.couchbase.com/sdk-api/couchbase-java-columnar-client-1.0.0/com/couchbase/client/java/index.html[API Reference]

// edit the links below
////
https://packages.couchbase.com/clients/java/3.7.0/Couchbase-Java-Client-3.7.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-java-client-3.7.0/index.html[API Reference]
////


// end::all[]
