= Full Installation
:description: Installation instructions for the {name-sdk}.
:page-partial:


[abstract]
{description}





== Before You Start


Currently Python 3.8 - Python 3.11 is supported.
Python 3.12 support is coming soon.


== Getting the SDK


Eventually the SDK will be published to PyPI, but in the interim a select set of wheels are available on the https://github.com/couchbaselabs/columnar-python-client/releases[GitHub Releases page].
If a wheel is not available for your specific Python version and/or platform,
See the https://github.com/couchbaselabs/columnar-python-client/blob/main/BUILDING.md[GitHub Building page] for details on how to build the SDK's binary.

To install the SDK from a wheel on the https://github.com/couchbaselabs/columnar-python-client/releases[GitHub Releases page]:

. Download the appropriate wheel
. Unzip the downloaded file
. Install via pip: `python3 -m pip install <path to unzipped wheel>`

If a compatible wheel is not available, the SDK's binary will need to be built from source:

* Follow the steps on the https://github.com/couchbaselabs/columnar-python-client/blob/main/BUILDING.md[GitHub Building page].
* After the build succeeds, the SDK can be used by running Python scripts from within the cloned repository -- or the SDK can be installed via pip: `python3 -m pip install <path to cloned repository>`


