= Hello Columnar -- Java SDK
:description: Install, connect, try. A quick start guide to get you up and running with Couchbase and the {name-sdk}.

[abstract]
{description}





== Before You Start

You will need Java 17 or later.
We recommend using the most recent long-term support (LTS) version of OpenJDK.

TIP: Remember to keep your Java installation up to date with the latest patches.

== Getting the SDK

Couchbase publishes all stable artifacts to https://central.sonatype.com/namespace/com.couchbase.client[Maven Central].

Use your favorite dependency management tool to include the SDK in your project.

[{tabs}]
====
Maven::
+
--
For https://maven.apache.org[Maven], add this to the `dependencies` section of your project's `pom.xml` file:

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>com.couchbase.client</groupId>
    <artifactId>couchbase-columnar-java-client</artifactId>
    <version>{sdk_current_version}</version>
</dependency>
----
Refer to the https://maven.apache.org/guides/introduction/introduction-to-the-pom.html/[Maven Documentation] for more information regarding the structure of the `pom.xml` file.
--
Gradle (Kotlin)::
+
--
For a https://gradle.org/[Gradle] script written in Kotlin, add this line to the `dependencies` section of your project's `build.gradle.kts` file:

[source,kotlin,subs="attributes+"]
----
implementation("com.couchbase.client:couchbase-columnar-java-client:{sdk_current_version}")
----
--
Gradle (Groovy)::
+
--
For a https://gradle.org/[Gradle] script written in Groovy, add this line to the `dependencies` section of your project's `build.gradle` file:

[source,groovy,subs="attributes+"]
----
implementation 'com.couchbase.client:couchbase-columnar-java-client:{sdk_current_version}'
----
--
====


[maven-project-template]
=== Maven Project Template

The SDK's source code repository includes an https://github.com/couchbase/couchbase-jvm-clients/tree/master/columnar-java-client/examples[example Maven project] you can copy to get started quickly.



[quickstart]
== Connecting and Executing a Query

[source,java]
----
import com.couchbase.columnar.client.java.Cluster;
import com.couchbase.columnar.client.java.Credential;
import com.couchbase.columnar.client.java.QueryResult;
import com.couchbase.columnar.client.java.internal.Certificates;

import java.util.List;

public class Example {
  public static void main(String[] args) {
    var connectionString = "couchbases://...";
    var username = "...";
    var password = "...";

    try (Cluster cluster = Cluster.newInstance(
      connectionString,
      Credential.of(username, password),
      clusterOptions -> clusterOptions
        // Configure a secure connection to a Couchbase internal pre-production cluster.
        // (Omit this when connecting to a production cluster!)
        .security(it -> it.trustOnlyCertificates(Certificates.getNonProdCertificates()))
    )) {

      // Execute a query and buffer all result rows in client memory.
      QueryResult result = cluster.executeQuery("select 1");
      result.rows().forEach(row -> System.out.println("Got row: " + row));

      // Execute a query and process rows as they arrive from server.
      cluster.executeStreamingQuery(
          "select 1",
          row -> System.out.println("Got row: " + row)
      );

      // Execute a streaming query with positional arguments.
      cluster.executeStreamingQuery(
        "select ?=1",
        row -> System.out.println("Got row: " + row),
        options -> options
          .parameters(List.of(1))
      );

      // Execute a streaming query with named arguments.
      cluster.executeStreamingQuery(
        "select $foo=1",
        row -> System.out.println("Got row: " + row),
        options -> options
          .parameters(Map.of("foo", 1))
      );
    }
  }
}
----
